version: "3"

tasks:
  default:
    cmds:
      - task --list

  check:
    desc: "{{ .DESC }}"
    summary: "{{ .DESC }}"
    vars:
      DESC: Lint and run tests
    cmds:
      - task: lint
      - task: test

  lint:
    desc: "{{ .DESC }}"
    summary: "{{ .DESC }}"
    vars:
      DESC: Lint the code using ruff
    cmds:
      - ruff check --fix
      - ruff format

  test:
    desc: "{{ .DESC }}"
    summary: "{{ .DESC }}"
    vars:
      DESC: Runs the tests
    cmds:
      - pytest

  testv:
    desc: "{{ .DESC }}"
    summary: "{{ .DESC }}"
    vars:
      DESC: Runs the tests with verbose output
    cmds:
      - pytest -vv

  install:
    desc: "{{ .DESC }}"
    summary: "{{ .DESC }}"
    vars:
      DESC: Install the dependencies using the tool uv. Create a venv first.
    cmds:
      - source .venv/bin/activate
      - uv pip install -r pyproject.toml --all-extras
      - uv pip install -e .

  build:
    desc: "{{ .DESC }}"
    summary: "{{ .DESC }}"
    vars:
      DESC: Build the package for distribution
    cmds:
      - rm -rf dist/**
      - python -m build

  bump:
    desc: "{{ .DESC }}"
    summary: "{{ .DESC }}"
    vars:
      DESC: Bump the version in ``libyear/__about__.py``
    cmds:
      - python scripts/version_bump.py
